# Generated by Django 4.2.3 on 2024-08-30 09:39

from django.db import migrations, models
import django.db.models.deletion
import ludo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='match_deposit_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='match_withdrawl_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('request_to_join', models.BooleanField(default=False)),
                ('accetp_to_play', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('joined_time', models.DateTimeField(blank=True, null=True)),
                ('result_updated', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('user_payment', models.BooleanField(default=False)),
                ('joined_user_payment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Price_cut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cut', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='result_cancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='result_loss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.IntegerField(null=True)),
                ('room_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ludo.price')),
            ],
        ),
        migrations.CreateModel(
            name='result_win',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to=ludo.models.upload_path)),
                ('result_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludo.price')),
            ],
        ),
    ]
