# Generated by Django 4.2.3 on 2024-08-30 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ludo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='result_win',
            name='won',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='result_loss',
            name='lost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='result_loss',
            name='result_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludo.price'),
        ),
        migrations.AddField(
            model_name='result_cancel',
            name='cancel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='result_cancel',
            name='result_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludo.price'),
        ),
        migrations.AddField(
            model_name='price',
            name='joined_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_joined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='price',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match_withdrawl_payment',
            name='price_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludo.price'),
        ),
        migrations.AddField(
            model_name='match_withdrawl_payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match_deposit_payment',
            name='price_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludo.price'),
        ),
        migrations.AddField(
            model_name='match_deposit_payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
